services:

  backend:
    build: ./WorkAssistAI
    ports:
      - "8000:8000"
    env_file:
      - ./WorkAssistAI/.env

  frontend:
    build: ./career-compass-ai-main
    ports:
      - "8080:80"
    depends_on:
      - backend
